# Generated by Django 3.1.3 on 2020-11-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modetation',
            new_name='moderation',
        ),
    ]
