# Generated by Django 3.1.3 on 2020-11-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201118_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usernet',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='male', max_length=8),
        ),
        migrations.AddField(
            model_name='usernet',
            name='technology',
            field=models.ManyToManyField(related_name='users', to='profiles.Technology'),
        ),
    ]
